# Site
name: "RAWRitsCloud"
title: "RAWRitsCloud"
description: "A guy blogging cloud!"
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: /
disqus: 'rawritscloud'
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  james:
    name: James Murray-Ferris
    display_name: James
    gravatar: 276438a1f866f154bb25afba1226a359
    email: james@rawritscloud.com
    twitter: https://twitter.com/rawritscloud
    facebook: https://www.facebook.com/rawritscloud
    insta: https://www.instagram.com/rawritscloud
    linkedin: https://www.linkedin.com/in/jrmurray86
    description: "Cloud Consultant working mainly in Azure and blogging his journey and hopefully dropping some useful bits of information on the way."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]