title: RAWRitsCloud
description: >- # this means to ignore newlines until "baseurl:"
  Just a guy blogging about his journey in the cloud,
  writting about Terraform, Azure DevOps, Azure and sometimes AWS
url: https://www.rawritscloud.com
permalink: ':title/'
baseurl: ""
site-twitter: rawritscloud #if your site has a twitter account, enter it here

# Author Settings
author: James Murray-Ferris # add your name
author-img: logo.png # add your photo
about-author: Just a guy blogging about his journey in the cloud, writting about Terraform, Azure DevOps, Azure and sometimes AWS. # add description
social-twitter: rawritscloud # add your Twitter handle
social-facebook: rawritscloud # add your Facebook handle
social-github: rawritscloud # add your Github handle
social-linkedin: jrmurray86 # add your Linkedin handle
social-email: james@rawritscloud.com # add your Email address

# Build settings
remote_theme: artemsheludko/flexible-jekyll
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"